export const ImmediateModeInstructions = [
  {
    opcode: "3E",
    mnemonic: "MVI A",
    description: "Load immediate data {data} to accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "06",
    mnemonic: "MVI B",
    description: "Load immediate data {data} to register B.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "0E",
    mnemonic: "MVI C",
    description: "Load immediate data {data} to register C.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "16",
    mnemonic: "MVI D",
    description: "Load immediate data {data} to register D.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "1E",
    mnemonic: "MVI E",
    description: "Load immediate data {data} to register E.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "26",
    mnemonic: "MVI H",
    description: "Load immediate data {data} to register H.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "2E",
    mnemonic: "MVI L",
    description: "Load immediate data {data} to register L.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "36",
    mnemonic: "MVI M",
    description:
      "Load immediate data {data} to memory location pointed by HL pair.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "01",
    mnemonic: "LXI B",
    description: "Load immediate 16-bit data to BC register pair.",
    bytes: 3,
    operands: ["data16"],
  },
  {
    opcode: "11",
    mnemonic: "LXI D",
    description: "Load immediate 16-bit data to DE register pair.",
    bytes: 3,
    operands: ["data16"],
  },
  {
    opcode: "21",
    mnemonic: "LXI H",
    description: "Load immediate 16-bit data to HL register pair.",
    bytes: 3,
    operands: ["data16"],
  },
  {
    opcode: "31",
    mnemonic: "LXI SP",
    description: "Load immediate 16-bit data to Stack Pointer.",
    bytes: 3,
    operands: ["data16"],
  },
  {
    opcode: "C6",
    mnemonic: "ADI",
    description: "Add immediate data {data} to accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "CE",
    mnemonic: "ACI",
    description: "Add immediate data {data} with carry to accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "D6",
    mnemonic: "SUI",
    description: "Subtract immediate data {data} from accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "DE",
    mnemonic: "SBI",
    description:
      "Subtract immediate data {data} with borrow from accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "E6",
    mnemonic: "ANI",
    description: "AND immediate data {data} with accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "EE",
    mnemonic: "XRI",
    description: "XOR immediate data {data} with accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "F6",
    mnemonic: "ORI",
    description: "OR immediate data {data} with accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
  {
    opcode: "FE",
    mnemonic: "CPI",
    description: "Compare immediate data {data} with accumulator A.",
    bytes: 2,
    operands: ["data"],
  },
];
